# -*- coding: utf-8 -*-
"""BoxplotPosture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KUUtd054aBVsJ6O5p3p5B_FzriupXudF
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

dataset = pd.read_csv("/content/gdrive/My Drive/Progetto Biometria/V.csv", delimiter=",", low_memory=False)

Length_data = dataset.groupby('Posture')
Length_data.boxplot(column='PairedVel80', grid=True)
plt.figure(figsize=(10, 10))
plt.show()