# -*- coding: utf-8 -*-
"""PostureV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z_3GYK2nDKqowkaRexnkLywvlE8M7VfQ
"""

from google.colab import drive
drive.mount('/content/gdrive')

import csv


with open('/content/gdrive/My Drive/Progetto Biometria/V.csv','r', errors='ignore') as f:

  Posture1_1 = open("/content/gdrive/My Drive/Progetto Biometria/Posture1_1.csv", 'w+')
  Posture2_2 = open("/content/gdrive/My Drive/Progetto Biometria/Posture2_2.csv", 'w+')
  Posture3_3 = open("/content/gdrive/My Drive/Progetto Biometria/Posture3_3.csv", 'w+')


  data = f.readlines()


  for i in range(1, 150206):

    elements = data[i].split(",")
    

    if "1" in elements[1]:
    
      Posture1_1.write(data[i])


    elif "2" in elements[1]:
      Posture2_2.write(data[i])
      

    else:
      Posture3_3.write(data[i])


  Posture1_1.close()
  Posture2_2.close()
  Posture3_3.close()

f.close()