# -*- coding: utf-8 -*-
"""PostureH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rqod9weObeJxzRH6VNX1TGdJ0l9nwHnz
"""

from google.colab import drive
drive.mount('/content/gdrive')

cd Progetto\ Biometria

import csv


with open('/content/gdrive/My Drive/Progetto Biometria/H.csv','r', errors='ignore') as f:

  Posture1 = open("/content/gdrive/My Drive/Progetto Biometria/Posture1.csv", 'w+')
  Posture2 = open("/content/gdrive/My Drive/Progetto Biometria/Posture2.csv", 'w+')
  Posture3 = open("/content/gdrive/My Drive/Progetto Biometria/Posture3.csv", 'w+')


  data = f.readlines()


  for i in range(1, 450367):

    elements = data[i].split(",")
    

    if "1" in elements[1]:
    
      Posture1.write(data[i])


    elif "2" in elements[1]:
      Posture2.write(data[i])
      

    else:
      Posture3.write(data[i])


  Posture1.close()
  Posture2.close()
  Posture3.close()

f.close()

